# Generated by Django 4.1.12 on 2023-10-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_search_search_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='destination_searches',
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_searchID',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_imageURL',
            field=models.URLField(null=True),
        ),
    ]
