# Generated by Django 4.1.12 on 2023-11-03 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destination_destination_imageurl_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='destination_likes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeDestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationLiked', to='destinations.destination')),
                ('likeUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
