# Generated by Django 4.1.12 on 2023-11-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_subscribedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='destination_imageURL',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_imageURL_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_imageURL_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_imageURL_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_imageURL_5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_imageURL_6',
            field=models.TextField(null=True),
        ),
    ]
