# Generated by Django 4.2.5 on 2023-10-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postLikes',
            field=models.IntegerField(null=True),
        ),
    ]
