# Generated by Django 4.2.5 on 2023-10-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_postlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postLikes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
