# Generated by Django 4.2.5 on 2023-09-30 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidListing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingBid', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
